### ISSUE TITLE
A user is able to see the trackers for which he/she doesn't have permission.

### ISSUE THREAD

**Issue by bellmanford** [voko/teamforge-cyloncloner#1]
After configuring any destination trackers and enable External cloning button for a project. If any user click on the External cloning button(by opening an artifact), user is able to see the trackers for which he/she doesn't have permission. Earlier in CTF version 8.0, user was not able to view the trackers for which he/she didn't had permission.

**Comment by voko** [comment]
Before cyloncloner 3.1.0, a normal user did not see the list of trackers if:
* the tracker list was explicitely set in the project settings
* she did not have permissions to access one of the named trackers

This is fixed in 3.1.0.
