### ISSUE TITLE
cloning does not restrict based on the tracker workflow. Ignores it.

### ISSUE THREAD

**Issue by remya-cn** [voko/teamforge-cyloncloner#3]
Steps to reproduce:
1. Create 2 trackers track1 and track2.
2. Create a role with tracker admin permission - adminRole.
3. Create another role with tracker edit/view permission - editRole.
4. Create a non-admin user user1.
5. Assign editRole to user1.
6. Create a workflow in track2 for create artifact such as a user having adminRole only can create an artifact in track2. (screenshot)
7. Now login as user1 and create an artifact in track1. Try to clone the artifact to track2.
8. It is getting cloned successfully. Whereas in the track2 artifact list page, create button is not displayed for user1.
![scr01](https://cloud.githubusercontent.com/assets/22339412/18700875/48151e66-7ff7-11e6-9028-14a837c0526a.png)

**Comment by voko** [comment]
Hey Remya, that is a really good one.
Actually I currently consider this a TF API issue. Cyloncloner only uses the createArtifact() API call and imho this call should fail in case of a workflow conflict.

Fixing this in cyloncloner would require a to implement shadow RBAC check/implementation/verification part which would just work around the underlying issue that the API allows actions against the constraints opposed be the workflow.

On could try to reproduce this using the CLI tool. I guess you simply can create a new artifact in track2 as user1, no need for the cloning steps.

Marked as wontfix.
