### ISSUE TITLE
UI issues in the clone pop-up window

### ISSUE THREAD

**Issue by remya-cn** [voko/teamforge-cyloncloner#4]
Found these two issues in the clone pop-up window.

1. Close icon is not clickable in the clone pop-up window
2. When some error occurs while cloning an artifact, if we close the pop-up window and click clone button in the artifact details page again without refreshing, the 'cloneIt' button in the pop-up window is not clickable.

**Comment by voko** [comment]
1 - fixed in 3.1.1
2 - fixed in 3.1.1
